[package]
name = "swarmonomicon"
version = "0.1.1"
edition = "2021"
authors = ["Danedens31@gmail.com"]
description = "A Rust implementation of an agent-based workflow system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["ws", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
tower = "0.4"
hyper = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
screenshots = "0.8"
lazy_static = "1.4"
browser-agent = {path = "./browser-agent"}

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"

[lib]
name = "swarmonomicon"
path = "src/lib.rs"

[[bin]]
name = "swarm"
path = "src/bin/swarm.rs"

[[bin]]
name = "todo_worker"
path = "src/bin/todo_worker.rs"
