[package]
name = "swarmonomicon"
version = "0.1.1"
edition = "2021"
authors = ["Danedens31@gmail.com"]
description = "Madness Interactive - Agent Swarm and Eventbase"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["git-agent", "haiku-agent", "greeter-agent", "browser-agent", "project-init-agent"]
git-agent = []
haiku-agent = []
greeter-agent = []
browser-agent = []
project-init-agent = []

# Dependencies required by browser-agent
browser-agent-deps = ["chromiumoxide", "chromiumoxide_cdp", "tokio-tungstenite"]

[dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
tower = "0.4"
hyper = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
rumqttc = "0.1"
futures = "0.3"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
screenshots = "0.8"
lazy_static = "1.4"
rand = "0.8"

# Optional dependencies for browser-agent
chromiumoxide = { version = "0.5", optional = true }
chromiumoxide_cdp = { version = "0.5", optional = true }
tokio-tungstenite = { version = "0.24", optional = true }

uuid = { version = "1.7.0", features = ["v4", "serde"] }

mongodb = { version = "2.0", features = ["bson-chrono-0_4"] }
async-std = "1.10"
futures-util = "0.3"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
tempfile = "3.8"

[lib]
name = "swarmonomicon"
path = "src/lib.rs"

[[bin]]
name = "swarm"
path = "src/bin/swarm.rs"

[[bin]]
name = "todo_worker"
path = "src/bin/todo_worker.rs"
