services:
  # Main MCP Todo Server service
  mcp_todo_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: swarmonomicon/mcp_todo_server:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - AI_ENDPOINT=http://host.docker.internal:11434/api/generate
      - AI_MODEL=qwen2.5-7b-instruct
      # Default remote MongoDB connection - can be overridden
      - RTK_MONGO_URI=${RTK_MONGO_URI:-mongodb://AWS_IP_ADDRESS:27017}
      - RTK_MONGO_DB=swarmonomicon
      # Default remote MQTT connection - can be overridden
      - MQTT_HOST=${AWSIP:-AWS_IP_ADDRESS}
      - MQTT_PORT=${AWSPORT:-1883}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    profiles:
      - all
      - default

  # Optional MongoDB for task storage (run with --profile mongodb)
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=swarmonomicon
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    profiles:
      - mongodb
      - all

  # Optional Mosquitto MQTT broker for messaging (run with --profile mqtt)
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -p 1883 -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
      interval: 600s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    profiles:
      - mqtt
      - all

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
